import { existsSync, readFileSync } from 'node:fs';
import { loadEnv } from 'vite';
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import basicSsl from '@vitejs/plugin-basic-ssl';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig(({ mode }) => {
  // Load .env* files so DEV_PROXY_TARGET set there configures the dev proxy.
  const env = loadEnv(mode, process.cwd(), '');
  // Where the Vite dev server forwards /socket.io + /health during development.
  // This is a Node-only value (deliberately NOT VITE_-prefixed) so it is never
  // inlined into the browser bundle: the browser always talks to the dev server
  // same-origin and Vite proxies from there. In the Docker dev stack this points
  // at the `server` service; on a bare host it defaults to localhost. An explicit
  // environment variable (e.g. from Docker Compose) wins over .env files.
  const PROXY_TARGET =
    process.env.DEV_PROXY_TARGET || env.DEV_PROXY_TARGET || 'http://localhost:3000';

  // Serve the dev server over HTTPS when DEV_HTTPS is set. The browser
  // Geolocation API only works in a secure context, so testing GPS from another
  // device on the LAN (http://<host-ip>:5173 is NOT secure) requires TLS.
  // Localhost dev needs none of this (localhost is already a secure context), so
  // this stays opt-in.
  const HTTPS = ['1', 'true', 'yes'].includes(
    (process.env.DEV_HTTPS || env.DEV_HTTPS || '').toLowerCase(),
  );

  // Prefer a locally-trusted cert generated by scripts/dev-certs.sh (mkcert), so
  // phones show NO certificate warning once they trust the mkcert root CA. If no
  // cert files are provided, fall back to plugin-basic-ssl's throwaway
  // self-signed cert (fine on localhost, but phones may refuse to bypass it).
  const CERT_FILE = process.env.DEV_HTTPS_CERT || env.DEV_HTTPS_CERT;
  const KEY_FILE = process.env.DEV_HTTPS_KEY || env.DEV_HTTPS_KEY;
  const hasCertFiles = Boolean(
    CERT_FILE && KEY_FILE && existsSync(CERT_FILE) && existsSync(KEY_FILE),
  );
  if (HTTPS && CERT_FILE && !hasCertFiles) {
    // Configured to use a cert but the files aren't there — most likely
    // `make dev-certs` hasn't been run. Warn and fall back to basic-ssl rather
    // than crashing the dev server on a missing file.
    console.warn(
      `[vite] DEV_HTTPS_CERT/KEY not found (${CERT_FILE}); run "make dev-certs".` +
        ' Falling back to a self-signed cert.',
    );
  }
  const httpsCert = hasCertFiles
    ? { cert: readFileSync(CERT_FILE as string), key: readFileSync(KEY_FILE as string) }
    : undefined;

  return {
    plugins: [
      react(),
      // Only need the self-signed fallback when HTTPS is on without a real cert.
      ...(HTTPS && !httpsCert ? [basicSsl()] : []),
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: ['favicon.png', 'apple-touch-icon.png'],
        manifest: {
          name: 'Manhunt',
          short_name: 'Manhunt',
          description: 'Web-based GPS hide-and-seek game',
          theme_color: '#06080c',
          background_color: '#06080c',
          display: 'standalone',
          orientation: 'portrait',
          icons: [
            { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            {
              src: 'pwa-maskable-512x512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'maskable',
            },
          ],
        },
      }),
    ],
    // The client is built into the repo-root `dist/`, which the server serves in
    // production and the Dockerfile copies into the runtime image.
    build: {
      outDir: '../dist',
      emptyOutDir: true,
    },
    server: {
      port: 5173,
      // Explicit cert (mkcert) wins; otherwise plugin-basic-ssl supplies one.
      ...(httpsCert ? { https: httpsCert } : {}),
      // Proxy the Socket.IO endpoint and the health check to the game server so
      // the dev client can reach them same-origin (no CORS, sockets upgrade).
      proxy: {
        '/socket.io': { target: PROXY_TARGET, ws: true, changeOrigin: true },
        '/health': { target: PROXY_TARGET, changeOrigin: true },
      },
    },
    test: {
      environment: 'jsdom',
      globals: true,
      setupFiles: ['./src/test/setup.ts'],
      include: ['src/**/*.{test,spec}.{js,jsx,ts,tsx}'],
      // Playwright specs live in e2e/ and must not be run by Vitest.
      exclude: ['e2e/**', 'node_modules/**', 'dist/**'],
    },
  };
});
