import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { loadEnv } from 'vite';
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import basicSsl from '@vitejs/plugin-basic-ssl';
import { VitePWA } from 'vite-plugin-pwa';
import { cloudflare } from '@cloudflare/vite-plugin';
import { releaseVersion } from '../scripts/release-version.ts';
import { workerRoutePatterns } from '../shared/routes.ts';

export default defineConfig(({ mode }) => {
  // Load .env* files so the DEV_HTTPS settings below can be set there too.
  const env = loadEnv(mode, process.cwd(), '');

  // Serve the dev server over HTTPS when DEV_HTTPS is set. The browser
  // Geolocation API only works in a secure context, so testing GPS from another
  // device on the LAN (http://<host-ip>:5173 is NOT secure) requires TLS.
  // Localhost dev needs none of this (localhost is already a secure context), so
  // this stays opt-in.
  const HTTPS = ['1', 'true', 'yes'].includes(
    (process.env.DEV_HTTPS || env.DEV_HTTPS || '').toLowerCase(),
  );

  // Prefer a locally-trusted cert generated by scripts/dev-certs.sh (mkcert), so
  // phones show NO certificate warning once they trust the mkcert root CA. If no
  // cert files are provided, fall back to plugin-basic-ssl's throwaway
  // self-signed cert (fine on localhost, but phones may refuse to bypass it).
  const CERT_FILE = process.env.DEV_HTTPS_CERT || env.DEV_HTTPS_CERT;
  const KEY_FILE = process.env.DEV_HTTPS_KEY || env.DEV_HTTPS_KEY;
  const hasCertFiles = Boolean(
    CERT_FILE && KEY_FILE && existsSync(CERT_FILE) && existsSync(KEY_FILE),
  );
  if (HTTPS && CERT_FILE && !hasCertFiles) {
    // Configured to use a cert but the files aren't there — most likely
    // `make dev-certs` hasn't been run. Warn and fall back to basic-ssl rather
    // than crashing the dev server on a missing file.
    console.warn(
      `[vite] DEV_HTTPS_CERT/KEY not found (${CERT_FILE}); run "make dev-certs".` +
        ' Falling back to a self-signed cert.',
    );
  }
  const httpsCert = hasCertFiles
    ? { cert: readFileSync(CERT_FILE as string), key: readFileSync(KEY_FILE as string) }
    : undefined;

  return {
    // Release version for the Worker's /health (tag, or `git describe` locally).
    define: {
      __MANHUNT_VERSION__: JSON.stringify(releaseVersion()),
    },
    plugins: [
      react(),
      // Runs the Worker and its Durable Objects in local workerd during `vite`
      // dev and builds the Worker next to the client. Client unit tests don't
      // need a Worker, so Vitest skips it.
      ...(process.env.VITEST ? [] : [cloudflare({ configPath: '../deploy/wrangler.jsonc' })]),
      // Only need the self-signed fallback when HTTPS is on without a real cert.
      ...(HTTPS && !httpsCert ? [basicSsl()] : []),
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: ['favicon.png', 'apple-touch-icon.png'],
        workbox: {
          // The service worker precaches the app shell (built JS/CSS/HTML, the
          // manifest, and the icons) so the client boots offline, and serves the
          // cached index.html for navigations (SPA deep links + offline
          // reloads). Exclude the Worker's own routes so an installed client
          // never shadows them with the app shell — the same list the Worker
          // answers, from shared/.
          navigateFallbackDenylist: workerRoutePatterns(),
          // Pull the Web Push listeners (push + notificationclick) into the
          // generated worker (BACKLOG.md #23). Workbox generates the offline
          // shell but knows nothing of push, so the handlers live in a plain
          // script in public/ and are imported here. See public/push-sw.js.
          importScripts: ['push-sw.js'],
        },
        manifest: {
          name: 'Manhunt',
          short_name: 'Manhunt',
          description: 'Web-based GPS hide-and-seek game',
          theme_color: '#06080c',
          background_color: '#06080c',
          display: 'standalone',
          orientation: 'portrait',
          icons: [
            { src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' },
            { src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            {
              src: 'pwa-maskable-512x512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'maskable',
            },
          ],
        },
      }),
    ],
    resolve: {
      // The wire protocol shared with the server lives outside this workspace.
      alias: { '@manhunt/shared': fileURLToPath(new URL('../shared/index.ts', import.meta.url)) },
    },
    // The client is built into the repo-root `dist/`, which the Worker serves as
    // its static assets and the Dockerfile copies into the runtime image.
    build: {
      outDir: '../dist',
      emptyOutDir: true,
    },
    // The Cloudflare plugin builds two environments: the PWA into the repo-root
    // `dist/` the Worker serves, and the Worker bundle (with its generated
    // wrangler.json, whose `assets.directory` points back at `dist/`) into
    // `dist-worker/`.
    environments: {
      client: { build: { outDir: '../dist' } },
      manhunt: { build: { outDir: '../dist-worker' } },
    },
    server: {
      port: 5173,
      // Explicit cert (mkcert) wins; otherwise plugin-basic-ssl supplies one.
      ...(httpsCert ? { https: httpsCert } : {}),
    },
    test: {
      environment: 'jsdom',
      globals: true,
      setupFiles: ['./src/test/setup.ts'],
      include: ['src/**/*.{test,spec}.{js,jsx,ts,tsx}'],
      // Playwright specs live in e2e/ and must not be run by Vitest.
      exclude: ['e2e/**', 'node_modules/**', 'dist/**'],
    },
  };
});
